name: Create Release & Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: |
          Package version to release
          * Semver, e.g. "1.2.3" or "1.2.3-beta.42"
          * Non-prerelease version tags MUST target the "develop" branch
          * Prerelease versions can be used for any target branch (e.g. "1.2.3-TA-555.1")

permissions:
  contents: write

jobs:
  validate_input:
    name: Validate input
    runs-on: ubuntu-latest
    steps:
      - name: Validate input version is valid semver
        run: |
          INPUT_VER="${{ github.event.inputs.version }}"
          if ! [[ "$INPUT_VER" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[[:alnum:]]+(\.[0-9]+)*)?$ ]]; then
            echo "::error::Version must be valid semver (e.g. 1.2.3 or 1.2.3-beta.1)"
            exit 1
          fi

      - name: Validate non-prerelease input version targets develop branch only
        run: |
          VERSION="${{ github.event.inputs.version }}"
          REF="${{ github.ref_name }}"
          if [[ ! "$VERSION" =~ - ]]; then
            if [[ "$REF" != "develop" ]]; then
              echo "::error ::Non-prerelease versions must be released from 'develop'."
              exit 1
            fi
          fi

  bump_version_and_push_tag:
    name: Bump Version & Push Tag
    needs: validate_input
    runs-on: ubuntu-latest

    outputs:
      version_tag_ref: ${{ steps.bump_version.outputs.version_tag_ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CONTENTS_WRITE_TOKEN }}

      - name: Bump version
        id: bump_version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --detach
          VERSION=$(npm version "${{ github.event.inputs.version }}")
          echo "version_tag_ref=$VERSION" >> $GITHUB_OUTPUT

      - name: Push tag
        id: push_tag
        run: |
          git push -u origin "${{ steps.bump_version.outputs.version_tag_ref }}"

  build_and_create_draft_release:
    name: Build & Create Draft Release
    needs: bump_version_and_push_tag
    runs-on: ubuntu-latest

    outputs:
      release_id: ${{ steps.create_draft_release.outputs.id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.bump_version_and_push_tag.outputs.version_tag_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Test
        run: |
          npm run test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-artifacts
          path: |
            dist-cjs
            dist-es
            dist-types
            LICENSE
            package-lock.json
            package.json
            README.md

      - name: Create draft GitHub Release
        id: create_draft_release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: ${{ contains(github.ref_name, '-') }}
          append_body: false
          body: 'Awaiting approval: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'

  approve_and_publish:
    name: Publish to NPM
    needs: build_and_create_draft_release
    runs-on: ubuntu-latest
    environment: release # this line causes a manual approval to be required

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: package-artifacts
          path: ./

      - name: Set up Node.js & NPM
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@bussin'
          always-auth: true

      - name: Publish to NPM
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish GitHub Release
        id: publish_release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          append_body: false
          body: |
            Package release complete!
            Approved: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
