name: Test semver action steps
run-name: Test '${{ inputs.version }}' - @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Version (semver)

jobs:
  test_actions:
    name: Test actions
    runs-on: ubuntu-latest

    steps:
      - name: matt-usurp
        id: matt-usurp
        uses: matt-usurp/validate-semver@v2
        with:
          version: ${{ github.event.inputs.version }}

      - name: print matt-usurp
        run: |
          echo "${{ steps.matt-usurp }}"
          echo "${{ toJson(steps.matt-usurp) }}"
          echo "${{ steps.matt-usurp.outputs }}"
          echo "${{ toJson(steps.matt-usurp.outputs) }}"
          echo "----------"
          echo "${{ steps.matt-usurp.conclusion }}"
          echo "${{ steps.matt-usurp.outcome }}"

      - name: zyactions
        id: zyactions
        uses: zyactions/semver@v1
        with:
          version: ${{ github.event.inputs.version }}

      - name: print zyactions
        run: |
          echo "${{ steps.zyactions }}"
          echo "${{ toJson(steps.zyactions) }}"
          echo "${{ steps.zyactions.outputs }}"
          echo "${{ toJson(steps.zyactions.outputs) }}"
          echo "----------"
          echo "${{ steps.zyactions.conclusion }}"
          echo "${{ steps.zyactions.outcome }}"
